### PR TITLE
Adding Explorer SideTab

### LINKED ISSUE #936: [Proposal] Explorer
Over at [OneGraph](https://github.com/OneGraph) we've built and just recently open sourced an Explorer plugin for GraphiQL: https://github.com/OneGraph/graphiql-explorer.

> Check out the [introduction blog post](https://www.onegraph.com/blog/2019/01/24/How_OneGraph_onboards_users_new_to_GraphQL.html) to learn why and how we built it and how it works.

After talking to @schickling, I would love to see adding it to the Playground as well, as [more and more people](https://github.com/OneGraph/graphiql-explorer/issues/3) are using it instead of GraphiQL. Porting should be fairly simple, but I might need some help with the styling.

I will add a PR that adds the explorer as is soon.
Some guidance and feedback would then be super useful. (cc @Huvik)

-----

Probably not related to this issue itself:

> **Note**: I did not check the source code yet, so if there already is something like that - forget about it.

Maybe we should think about some kind of plugin system? Seeing #935 and having some more stuff coming up soon, it might be useful to have a simple way to add those.
Might be enough to register a menu button that toggles a panel which is passed all the available data.

### PR DESCRIPTION
**Pull request by rofrischmann**
> **WIP**: This is far from ready. Just created the PR to keep track of what's left todo.

Fixes #936 .

Changes proposed in this pull request:

- Adds another side tab that includes [graphiql-explorer](https://github.com/OneGraph/graphiql-explorer)

## ToDo
- [ ] Proper Typings
- [ ] Tab Colors
- [ ] Render Explorer with correct query/schema
- [ ] Updating query on change
- [ ] **Blocked**: Explorer Styling (requires changes at the Explorer itself first)

### CODE REVIEW

**Comment by robsontenorio** [comment]
Any updates ?

**Comment by Huvik** [comment]
Hey @rofrischmann, I was wondering if I could help you somehow? Did you get stuck or something? If you need any help from my side ping me at Prisma slack as @huv1k

**Comment by FluorescentHallucinogen** [comment]
@dwwoelfel @sgrove PTAL. Any progress? I'm very excited about this feature. :)

**Comment by rofrischmann** [comment]
Sorry for not responding for so long.
I'm going to close this PR in favour of a more Playground-specific Explorer implementation which I planned for version 2. (cc @schickling)
Meanwhile, one might just use GraphiQL with the Explorer plugin enabled.

**Comment by schickling** [comment]
While the timeline is still up in the air, here is a design sneak peek of the explorer features as a part of the next version of the Playground 👀 

image

**Comment by FluorescentHallucinogen** [comment]
@schickling Hmm, very interesting! I'm with @rohit-ravikoti working on a package for visualizing any GraphQL API as an interactive GraphQL in 3D (including VR/AR). Here was my vision (left side tabs):

graphql-3d

**Comment by tomtev** [comment]
@schickling Looks amazing. When is 2.0 due?

**Comment by LuckyLuky** [comment]
Any update on the timeline?

**Comment by nksaraf** [comment]
I am pretty excited about adding this feature, can I help in any way, maybe with the development of version 2.0 (couldn't find it anywhere)

**Comment by robsontenorio** [comment]
@schickling is that available in some repo?

@FluorescentHallucinogen is that available in some repo?

**Pull request closed without merging**
