### PR TITLE
Schema polling feature

### PR DESCRIPTION
**Pull request by rohit-ravikoti**
Fixes #.

Changes proposed in this pull request:

- Implements a new feature where a schema can be reloaded on an interval.
screen shot 2019-01-07 at 1 47 30 pm

- The feature is currently enabled by default and can be configured in the settings tab. A new variable was added to the configuration called `schema.enablePolling` to toggle the feature.
screen shot 2019-01-07 at 1 50 16 pm

- When the feature is enabled, the reload icon turns green and has a subtle glow effect.

- The polling interval is every 2000ms.

- The schema only updates in the playground's state if there has been a change. The main reason for this is to keep a smooth UI for the docs explorers. Currently, if the schema updates, the search bar in the DOCS tab gets cleared and the content in the SCHEMA tab scrolls to the top.

### CODE REVIEW

**Comment by rohit-ravikoti** [comment]
@kuldar, thanks for the input! Are you saying that rather than automatically refreshing the schema, we indicate that there is an update and let them click to update it?

**Comment by rohit-ravikoti** [comment]
Thanks!  I'll look into adding the manual reload for schema and SDL tabs. I have a couple of questions:

- You were mentioning something about highlighting the schema polling state. Should we just keep a non-interactive refresh icon without any highlighting when polling is enabled?
- Currently, polling is enabled by default and can be disabled by setting the `schema.enablePolling` variable to false. Is this behavior okay with you?

Here is how I am imagining it to be working so far based on your feedback:
- The query editor will automatically update to show the new suggestions.
- The SCHEMA and SDL tabs will show a "Refresh to see changes" notice to update manually.
- Refresh icon will not be as prominent as it is now, but will instead be a non-interactive icon.

I will get started working toward the changes I mentioned above, but please feel free to make any corrections 😄

**Comment by kuldar** [comment]
Yes, I think we're pretty much on the same page. 

I originally also suggested to maybe remove the refresh icon/button altogether, but I noticed now that we've always had the refresh button, just on the other side. So I think your proposal in previous comment makes sense - we'd just show the gray refresh icon next to the url and spin it whenever fetching happens. I would probably not make it green though and keep it in the same gray tone as it is currently.

**Comment by rohit-ravikoti** [comment]
Hi @kuldar,
Here are the changes I made according to your feedback:

- The refresh icon now spins whenever fetching happens. However, it feels a bit distracting and it might make sense to use a non-animated icon.
- When the schema updates and the SCHEMA tab is open, a "Refresh to see changes" button becomes visible. When the button is clicked, the schema will be updated and the panel will scroll to the top.
- When the schema updates while the SCHEMA tab is collapsed, the new schema will be automatically used when the tab is opened.

**Comment by kuldar** [comment]
Yes, I think that's the perfect behaviour. I'm also not against removing the animation. Thank you! 👍

**Comment by Huvik** [comment]
Everything looks solid from my point of view.

**Comment by rohit-ravikoti** [comment]
Awesome! I'll go ahead and stop the animation and keep the icon static. Let me know if you would like to use a different icon to indicate polling.

**Comment by rohit-ravikoti** [comment]
Decided to go with #934 instead of this one.

**Pull request closed without merging**
